# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-12909-trinity/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/814a/hdl/verilog
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/1017/hdl/verilog
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/8745/hdl/verilog
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/2340/hdl/verilog
  } {
      /opt/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/814a/hdl/verilog
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/1017/hdl/verilog
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/8745/hdl/verilog
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/2340/hdl/verilog
  } {
      ./.Xil/Vivado-12909-trinity/realtime/riscv_data_memory_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_reg32_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_reg32_0_1_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_1_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_2_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_3_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_4_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_5_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_6_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_7_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_8_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_9_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_10_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_11_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_12_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_13_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_14_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_15_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_16_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_17_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_18_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_19_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_20_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_21_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_22_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_23_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_24_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_25_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_26_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_27_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_28_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_29_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_x1_30_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_decoder5_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s5_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s5_0_1_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_ila_0_2_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_cla32_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s1_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_sll_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_1_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_slt_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_1_1_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_srl_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_sra_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s1_1_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_1_2_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_2_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s3_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_reduced_logic_0_2_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_1_3_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_0_1_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_0_2_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_0_3_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_2_1_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_1_4_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_1_5_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_5_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_5_1_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_5_2_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_dist_mem_gen_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_control_unit_0_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_cla32_0_2_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s1_0_1_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s1_0_2_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_0_4_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_beq_0_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_beq_1_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_beq_2_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_beq_3_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_beq_4_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_reduced_logic_0_3_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_0_5_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_1_6_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_0_6_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_2_2_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s1_0_3_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s1_0_4_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_util_vector_logic_0_7_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s1_0_5_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s1_1_1_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s1_0_6_stub.v
      ./.Xil/Vivado-12909-trinity/realtime/riscv_mux_d32_s1_1_2_stub.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/data_memory.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/reg32.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/decoder5.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/mux_d32_s5.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/full_adder.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/half_adder.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/add32.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/mux_d32_s1.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/sll.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/srl.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/sra.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/mux_d32_s3.v
      /home/dishoungh/workspace/cpu/cpu.srcs/sources_1/new/control_unit.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/synth/riscv.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/hdl/riscv_top.v
    }
      rt::read_verilog -include {
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/814a/hdl/verilog
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/1017/hdl/verilog
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/8745/hdl/verilog
    /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/2340/hdl/verilog
  } {
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlconstant_0_1/synth/riscv_xlconstant_0_1.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlconstant_0_2/synth/riscv_xlconstant_0_2.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlconstant_1_0/synth/riscv_xlconstant_1_0.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/a97c/hdl/xlslice_v1_0_vl_rfs.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlslice_0_0/synth/riscv_xlslice_0_0.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ipshared/6120/hdl/xlconcat_v2_1_vl_rfs.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlconcat_0_0/synth/riscv_xlconcat_0_0.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlconstant_0_3/synth/riscv_xlconstant_0_3.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlconcat_0_1/synth/riscv_xlconcat_0_1.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlslice_1_0/synth/riscv_xlslice_1_0.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlslice_0_1/synth/riscv_xlslice_0_1.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlslice_0_2/synth/riscv_xlslice_0_2.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlslice_0_3/synth/riscv_xlslice_0_3.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlslice_0_5/synth/riscv_xlslice_0_5.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlconstant_0_6/synth/riscv_xlconstant_0_6.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_constant_4_0/synth/riscv_constant_4_0.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlslice_0_6/synth/riscv_xlslice_0_6.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlslice_0_7/synth/riscv_xlslice_0_7.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlslice_0_8/synth/riscv_xlslice_0_8.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlconcat_0_2/synth/riscv_xlconcat_0_2.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlconstant_0_7/synth/riscv_xlconstant_0_7.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlconcat_0_3/synth/riscv_xlconcat_0_3.v
      /home/dishoungh/workspace/cpu/cpu.gen/sources_1/bd/riscv/ip/riscv_xlslice_0_9/synth/riscv_xlslice_0_9.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top riscv_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-12909-trinity/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
